version: '3.6'

services:
  api:
    build: .  
    container_name: app_ts_express
    volumes:
      - ./:/app
      - ./node_modules:/app/node_modules
    ports:
      - 3000:3000
volumes:
  node_modules:
  